/* Browser adapter: the timing rules live in game-core.js. No build or CDN required. */
(() => {
  'use strict';
  const A=window.HeroAnimation,E=window.EnemyAnimation,C=window.HeroCore, $=id=>document.getElementById(id);
  const canvas=$('arena'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
  let run=null,screen='title',paused=false,holdStart=0,animationTime=0,impactShown=false,warningTime=0,stageTime=0;
  let titleClockStart=performance.now(),guardVisualStart=0;
  let fatalAttackTime=null,deathTime=null,deathTitlePlayed=false,revealTime=null;
  let previous=performance.now(),visualTime=0,holdVisualTime=0,activeInput=null,loaded=false,settings={bgm:.35,se:.55,difficulty:C.CONFIG.defaultDifficulty,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches};
  try{const saved=JSON.parse(localStorage.getItem('one-second-hero-settings'));if(saved&&typeof saved==='object'){for(const key of ['bgm','se'])if(Number.isFinite(saved[key]))settings[key]=Math.max(0,Math.min(1,saved[key]));if(typeof saved.reduced==='boolean')settings.reduced=saved.reduced;settings.difficulty=C.difficulty(saved.difficulty);}}catch{}
  const images={},audio=new window.HeroSound(settings,()=>{$('footer-status').textContent='音声を読み込めませんでした。オプションで再確認できます。';});
  function blind(){return run&&!C.DIFFICULTIES[run.difficulty].gauge;}
  function clearTiming(){$('timing-value').textContent='';$('timing-result').classList.add('empty');$('timing-result').setAttribute('aria-hidden','true');}
  function showTiming(seconds){$('timing-value').textContent=C.timingDisplay(seconds).value;$('timing-result').classList.remove('empty');$('timing-result').removeAttribute('aria-hidden');}
  function nextAction(){return run.phase==='result'?(run.last.mode==='attack'&&run.attacksSinceGuard>=C.CONFIG.attackEvery?'defense':'attack'):run.mode;}
  function buttonState(locked,label='長押し',mode=run.mode){const guard=mode==='defense';$('action-button').disabled=locked;$('action-button').classList.toggle('locked',locked);$('button-lock').hidden=!locked;$('button-label').textContent=label;$('button-subtitle').textContent=locked?(deathTime!==null||fatalAttackTime!==null||run.enemyHp===0?'PLEASE WAIT':guard?'NEXT : GUARD':'NEXT : ATTACK'):'HOLD & RELEASE';$('action-art').src=guard?'./assets/ui/Shield_button.png':'./assets/ui/Attack_button.png';}
  function fadeScene(opacity){$('scene-fade').style.opacity=String(opacity);$('scene-fade').classList.toggle('active',opacity>0);}
  function beginFatalAttack(){fatalAttackTime=0;impactShown=false;buttonState(true,'演出中','defense');$('arena-banner').textContent='';$('death-label').hidden=true;}
  function beginDeath(){fatalAttackTime=null;deathTime=0;deathTitlePlayed=false;audio.silenceAll();hud();$('arena-banner').textContent='';$('hit-label').textContent='';$('turn-hint').textContent='';$('death-label').hidden=true;buttonState(true,'倒れた…');$('action-instruction').textContent='冒険の終わり';}
  function saveSettings(){try{localStorage.setItem('one-second-hero-settings',JSON.stringify(settings));}catch{}}
  function applySettings(){$('music-player').disabled=screen!=='title';$('music-select').value=audio.current||'title';document.body.classList.toggle('reduced-motion',settings.reduced);$('bgm-volume').value=Math.round(settings.bgm*100);$('se-volume').value=Math.round(settings.se*100);$('bgm-value').textContent=Math.round(settings.bgm*100)+'%';$('se-value').textContent=Math.round(settings.se*100)+'%';$('reduced-motion').checked=settings.reduced;document.querySelector(`input[name="difficulty"][value="${settings.difficulty}"]`).checked=true;$('selected-difficulty').textContent=`難易度：${C.DIFFICULTIES[settings.difficulty].name} · オプションで変更できます`;$('difficulty-note').textContent=run&&screen!=='title'?`現在：${C.DIFFICULTIES[run.difficulty].name}。変更はタイトルから始める次の冒険に適用（敗北後の再挑戦では維持）。`:'選んだ難易度で冒険を開始します。HPは全難易度で持ち越します。';}
  $('music-select').innerHTML=Object.entries(window.HeroSound.music).map(([key,name])=>`<option value="${key}">${name}.mp3</option>`).join('');
  $('music-select').addEventListener('change',e=>{if(screen!=='title')return;audio.change(e.target.value);audio.unlock();});
  applySettings();
  function setScreen(name){if(name==='title'&&screen!=='title')titleClockStart=performance.now();screen=name;for(const s of ['title','play','shop','end'])$(s+'-screen').hidden=s!==name;window.scrollTo({top:0,behavior:'instant'});}
  function hud(){if(!run)return;const enemy=C.ENEMIES[run.stage];$('stage-number').textContent=String(run.stage+1).padStart(2,'0');$('stage-title').textContent=enemy.title;$('region-label').textContent=({plains:'THE GREENLANDS',desert:'THE AMBER DUNES',volcano:'THE EMBER PASS',demon_castle:'THE LAST CITADEL'})[enemy.region];$('enemy-name').textContent=enemy.name;$('hero-hp-text').textContent=`${run.hp} / ${C.CONFIG.maxHp}`;$('enemy-hp-text').textContent=`${run.enemyHp} / ${enemy.hp}`;$('hero-hp').style.width=run.hp+'%';$('enemy-hp').style.width=(run.enemyHp/enemy.hp*100)+'%';$('gold-display').textContent=run.gold+' G';$('enemy-flavor').textContent=enemy.flavor;$('route').innerHTML=C.ENEMIES.map((_,i)=>`<i class="${i<run.stage?'done':i===run.stage?'current':''}"></i>`).join('');$('route').setAttribute('aria-label',`10ステージ中 ${run.stage+1}ステージ目`);}
  function readyUI(reset=true){if(fatalAttackTime!==null){buttonState(true,'演出中','defense');return;}if(deathTime!==null){buttonState(true,'倒れた…');$('action-instruction').textContent='冒険の終わり';return;}const guard=run.mode==='defense',level=C.DIFFICULTIES[run.difficulty];$('control-panel').classList.toggle('defense',guard);$('control-panel').classList.toggle('blind-mode',blind());$('difficulty-badge').textContent=level.name;const band=document.querySelector('.dial-window'),length=647.168*(level.windows[0]*2/1.5);band.style.strokeDasharray=`${length} ${647.168-length}`;band.style.strokeDashoffset=String(-647.168*(1-level.windows[0])/1.5);$('mode-label').textContent=guard?'SHIELD / 防御':'SWORD / 攻撃';$('action-instruction').textContent=guard?'1秒で離して防御！':'1秒で離して攻撃！';$('action-icon').setAttribute('href',guard?'#icon-shield':'#icon-sword');$('action-button').setAttribute('aria-label',guard?'長押しして1秒で離すと防御':'長押しして1秒で離すと攻撃');const locked=paused||run.phase!=='ready';buttonState(locked,locked?'演出中':'長押し',nextAction());$('arena-banner').textContent=deathTime!==null?'':guard?'攻撃を防げ！':C.ENEMIES[run.stage].title;$('arena-banner').classList.toggle('warning',guard);$('turn-hint').textContent=guard?'盾も、同じ一秒で。':'一秒に、集中。';$('defense-pips').innerHTML=[0,1,2].map(i=>`<i class="${i<run.attacksSinceGuard?'on':''}"></i>`).join('');$('defense-count').textContent=guard?'ガード！':`あと${3-run.attacksSinceGuard}回`;
    if(reset){if(!run.last)clearTiming();$('result-line').textContent=blind()?'自分の感覚だけで、一秒を。':guard?'盾の準備ができたら、長押し':'光を1.0の目印に合わせよう';$('result-line').className='result-line';$('dial-progress').style.strokeDashoffset='647.168';$('hit-label').textContent='';$('dial-wrap').classList.remove('flash-success');}
  }
  function startStage(){setScreen('play');stageTime=0;warningTime=0;animationTime=0;fatalAttackTime=null;deathTime=null;revealTime=null;$('death-label').hidden=true;fadeScene(0);hud();readyUI();audio.change(run.stage===9?'boss':'battle');$('footer-status').textContent='タッチ / マウス / Space';}
  function newRun(sound='ui_confirm'){run=C.createRun(settings.difficulty);activeInput=null;audio.unlock();audio.playSE(sound);startStage();}
  function startHold(){if(paused||screen!=='play'||!C.begin(run))return false;audio.unlock();holdStart=performance.now();holdVisualTime=visualTime;$('action-button').classList.add('holding');$('button-label').textContent='1秒で離す';$('result-line').textContent='';$('result-line').className='result-line';$('dial-wrap').classList.remove('flash-success');clearTiming();$('hit-label').textContent='';audio.startHold(blind());return true;}
  function releaseHold(timeout=false){if(!run||run.phase!=='holding')return;const seconds=Math.min(C.CONFIG.maxHold,Math.max(0,(performance.now()-holdStart)/1000));const result=C.resolve(run,seconds,timeout);if(!result)return;animationTime=0;impactShown=false;$('action-button').classList.remove('holding');buttonState(true,run.enemyHp===0?'撃破！':'演出中',nextAction());showTiming(seconds);if(!blind())$('dial-progress').style.strokeDashoffset=String(647.168*(1-seconds/1.5));$('result-line').textContent=`${result.grade} · ${C.timingDisplay(seconds,timeout).hint}`;$('result-line').className='result-line '+(result.grade==='PERFECT'?'perfect':result.grade==='MISS'?'miss':'');if(result.grade==='PERFECT')$('dial-wrap').classList.add('flash-success');audio.result(result.grade,result.mode);if(result.mode==='attack'&&run.enemyHp===0){audio.playSE('enemy_defeat');$('arena-banner').textContent='敵を倒した！';}if(run.hp===0)beginFatalAttack();}
  function cancelHold(){audio.stopHold();if(run&&C.cancel(run)){activeInput=null;$('action-button').classList.remove('holding');readyUI();}}
  const button=$('action-button');
  button.addEventListener('pointerdown',e=>{if(!e.isPrimary||e.button!==0||activeInput!==null)return;e.preventDefault();if(startHold()){activeInput={type:'pointer',id:e.pointerId};button.setPointerCapture(e.pointerId);}});
  button.addEventListener('pointerup',e=>{if(activeInput?.type!=='pointer'||activeInput.id!==e.pointerId)return;e.preventDefault();releaseHold();activeInput=null;});
  button.addEventListener('pointercancel',()=>cancelHold());button.addEventListener('lostpointercapture',()=>{if(activeInput?.type==='pointer'){cancelHold();activeInput=null;}});button.addEventListener('contextmenu',e=>e.preventDefault());
  document.addEventListener('keydown',e=>{if(e.code!=='Space'||screen!=='play'||paused||e.target.closest('dialog')||(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))||(e.target.tagName==='BUTTON'&&e.target!==button))return;e.preventDefault();if(!e.repeat&&activeInput===null&&startHold())activeInput={type:'key'};});
  document.addEventListener('keyup',e=>{if(e.code!=='Space'||activeInput?.type!=='key')return;e.preventDefault();releaseHold();activeInput=null;});
  function pauseGame(dialogId){if(paused)return;cancelHold();paused=true;audio.pause();if(dialogId==='settings-dialog'){applySettings();audio.resume();audio.unlock();}if(screen==='play')buttonState(true,'一時停止',nextAction());$(dialogId).showModal();}
  function resumeGame(){paused=false;previous=performance.now();activeInput=null;audio.resume();audio.unlock();if(screen==='play')readyUI(false);}
  $('pause-button').addEventListener('click',()=>pauseGame('pause-dialog'));
  $('resume-button').addEventListener('click',()=>$('pause-dialog').close());
  $('pause-dialog').addEventListener('close',resumeGame);
  $('settings-open').addEventListener('click',()=>pauseGame('settings-dialog'));
  $('settings-dialog').addEventListener('close',()=>{saveSettings();resumeGame();});
  $('bgm-volume').addEventListener('input',e=>{settings.bgm=Number(e.target.value)/100;applySettings();audio.volumesChanged();saveSettings();});
  $('se-volume').addEventListener('input',e=>{settings.se=Number(e.target.value)/100;applySettings();audio.volumesChanged();saveSettings();});
  function previewSE(){audio.unlock();audio.stopSE('relive');audio.playSE('relive');}
  $('se-volume').addEventListener('change',previewSE);
  $('se-preview').addEventListener('click',previewSE);
  document.querySelectorAll('input[name="difficulty"]').forEach(input=>input.addEventListener('change',()=>{settings.difficulty=C.difficulty(input.value);applySettings();saveSettings();}));
  $('reduced-motion').addEventListener('change',e=>{settings.reduced=e.target.checked;applySettings();saveSettings();});
  document.addEventListener('visibilitychange',()=>{if(document.hidden){if(screen==='play'&&!paused)pauseGame('pause-dialog');else audio.pause();}else if(!paused||$('settings-dialog').open)audio.resume();});
  window.addEventListener('blur',()=>{if(screen==='play'&&!paused)pauseGame('pause-dialog');});
  document.addEventListener('pointerdown',()=>{if(!document.hidden&&!paused)audio.unlock();},{passive:true});
  $('start-button').addEventListener('click',()=>{if(loaded)newRun();});
  $('shop-return').addEventListener('click',()=>{if(C.next(run)){audio.playSE('ui_confirm');startStage();}});
  $('retry-button').addEventListener('click',()=>{if(run.phase==='clear')newRun('relive');else if(C.retry(run)){audio.playSE('relive');startStage();}});
  $('end-title-button').addEventListener('click',()=>{setScreen('title');applySettings();audio.playSE('ui_confirm');audio.change('title');$('footer-status').textContent='一秒から、また始めよう。';});
  $('credits-button').addEventListener('click',()=>{audio.change('credits');$('epilogue-dialog').showModal();$('epilogue-text').scrollTop=0;$('epilogue-text').focus();});
  $('epilogue-close').addEventListener('click',()=>$('epilogue-dialog').close());
  function shop(){audio.stopSE('enemy_defeat');setScreen('shop');audio.change('shop');$('shop-description').textContent=`STAGE ${String(run.stage+1).padStart(2,'0')} CLEAR · ${C.ENEMIES[run.stage].name}を倒した！ +${run.last.reward} G`;$('shop-message').textContent=`残りHP ${run.hp} / ${C.CONFIG.maxHp} · 体力は次のステージへ持ち越します。`;renderShop();$('footer-status').textContent='FAIRY TREE EMPORIUM';}
  function renderShop(){
    $('shop-gold').textContent=run.gold;
    const data=[['attack','攻撃','SWORD',level=>`攻撃力 ${C.attackPower(level)}`],['defense','防御','SHIELD',level=>`被ダメージ ${Math.round(C.defenseFactor(level)*100)}%`],['gold','金銭アップ','FORTUNE',level=>`獲得金額 ×${C.goldFactor(level).toFixed(1)}`]];
    $('shop-cards').innerHTML=data.map(([key,label,en,effect])=>{const lv=run.levels[key],cost=C.price(key,lv),max=cost===null;return `<article class="shop-card"><h2>${label}</h2><span class="item-en">${en}</span><div class="lamp-ring" aria-label="レベル${lv}、最大10"><img src="./assets/ui/item_${key==='attack'?'sword':key==='defense'?'shield':'money'}.png" alt="">${Array.from({length:10},(_,i)=>`<i class="${i<lv?'on':''}" style="transform:rotate(${-135+i*30}deg) translateY(-46px)"></i>`).join('')}<b>Lv ${lv} / 10</b></div><p class="item-effect">${effect(lv)}</p><p class="item-next">${max?'力は、最高の領域へ。':'次：'+effect(lv+1)}</p><button class="buy-button" data-buy="${key}" ${max||run.gold<cost?'disabled':''}>${max?'MAX':cost+' G'}<small>${max?'最大レベル':run.gold<cost?'所持金不足':'強化する'}</small></button></article>`;}).join('');
  }
  $('shop-cards').addEventListener('click',e=>{const target=e.target.closest('[data-buy]');if(!target)return;const key=target.dataset.buy;if(C.buy(run,key)){audio.playSE('shop_buy');renderShop();$('shop-message').textContent=`${{attack:'攻撃',defense:'防御',gold:'金銭アップ'}[key]}がLv ${run.levels[key]}になりました。残りHP ${run.hp}を持ち越します。`;const nextButton=$('shop-cards').querySelector(`[data-buy="${key}"]`);if(nextButton&&!nextButton.disabled)nextButton.focus({preventScroll:true});else $('shop-return').focus({preventScroll:true});}});
  function end(clear){audio.stopSE('enemy_defeat');setScreen('end');if(clear)audio.change('clear');else if(audio.current!=='over')audio.change('over');$('end-art').src=clear?'./assets/backgrounds/allclear512.png':'./assets/backgrounds/gameover512.png';$('end-art').alt=clear?'夜明けを迎えた世界と魔王城':'暗い空の下、不気味な魔王城';$('end-screen').classList.toggle('game-over',!clear);$('end-eyebrow').textContent=clear?'ALL CLEAR / A NEW DAWN':'TRY AGAIN / THE JOURNEY CONTINUES';$('end-title').textContent=clear?'その一秒が、世界を救った。':'まだ、旅は終わらない。';$('end-message').textContent=clear?'魔王を倒し、世界に朝が訪れた。\nあなたの剣と盾に、祝福を。':`${C.ENEMIES[run.stage].name}に敗れました。\n強化と所持金を引き継ぎ、HPを回復してステージ1から再挑戦します。`;$('score-panel').hidden=!clear;if(clear){const score=run.score;$('final-score').textContent=score.total.toLocaleString('ja-JP');$('score-breakdown').innerHTML=`<p>残りG ${score.gold.toLocaleString('ja-JP')} × PERFECT ${score.perfects}回 = ${score.goldBase.toLocaleString('ja-JP')}</p><p>精度ボーナス ${score.accuracyBonus.toLocaleString('ja-JP')} + 残りHPボーナス ${score.hpBonus.toLocaleString('ja-JP')} + クリア ${score.clearBonus.toLocaleString('ja-JP')}</p><p>難易度 ×${score.difficultyMultiplier} · 手数係数 ×${score.actionFactor.toFixed(3)} · 挑戦 ${score.attempts}周で補正</p>`;}$('end-stats').innerHTML=`<div><b>${run.stats.attacks}</b><span>攻撃</span></div><div><b>${run.stats.perfects}</b><span>PERFECT</span></div><div><b>${run.gold}</b><span>残り GOLD</span></div>`;$('retry-button').textContent=clear?'最初から、新しい冒険へ':'強化を引き継いでステージ1へ';$('credits-button').hidden=!clear;$('footer-status').textContent=C.DIFFICULTIES[run.difficulty].name+(clear?' · THANK YOU FOR PLAYING':' · 次は、きっと。');}

  // Ground anchors stay fixed while source cells and drawing scales vary.
  function drawHero(action,frame,x=72,y=107){const img=images['hero_'+action],s=A.renderScale;if(!img)return;frame=Math.max(0,Math.min(A.animations[action].frames-1,frame));ctx.drawImage(img,(frame%8)*256,Math.floor(frame/8)*256,256,256,x+64-A.anchorX*s,y+122-A.groundY*s,256*s,256*s);}
  function drawEnemy(id,row,frame,x,y,alpha=1){const a=E.specs[id],img=images[id];if(!img)return;ctx.save();ctx.globalAlpha=alpha;ctx.drawImage(img,frame*a.cell,row*a.cell,a.cell,a.cell,x+64-a.anchorX*a.scale,y+122-a.groundY*a.scale,a.cell*a.scale,a.cell*a.scale);ctx.restore();}
  function renderFatalAttack(){const enemy=C.ENEMIES[run.stage],pose=C.fatalAttackPose(fatalAttackTime);ctx.drawImage(images['bg_'+enemy.region],0,0,512,336);const action=pose.impact?'break':'guard',elapsed=pose.impact?fatalAttackTime-C.SCENE_TIMES.fatalFastFrame*2:A.duration('guard');drawHero(action,A.frame(action,elapsed));drawEnemy(enemy.id,2,pose.frame,316-pose.offset,107);}
  function advanceFatalAttack(dt){fatalAttackTime+=dt;const pose=C.fatalAttackPose(fatalAttackTime);if(pose.impact&&!impactShown){impactShown=true;hud();audio.playSE('hero_damage');$('hit-label').textContent='−'+run.last.damage;$('hit-label').style.color='#ffa8a0';}if(pose.done)beginDeath();}
  function renderDeath(){const enemy=C.ENEMIES[run.stage];ctx.fillStyle='#000';ctx.fillRect(0,0,512,336);drawHero('down',A.frame('down',deathTime));drawEnemy(enemy.id,2,3,224,107);}
  function advanceDeath(dt){const t=C.SCENE_TIMES;deathTime+=dt;const titleAt=t.deathFall+t.deathHold,fadeAt=titleAt+t.deathTitle;if(!deathTitlePlayed&&deathTime>=titleAt){deathTitlePlayed=true;$('death-label').hidden=false;audio.change('over');}if(deathTime>=fadeAt)fadeScene(Math.min(1,(deathTime-fadeAt)/t.deathFade));if(deathTime>=fadeAt+t.deathFade){C.finish(run);deathTime=null;end(false);fadeScene(1);revealTime=0;}}
  function render(){if(!run||!loaded||screen!=='play')return;if(fatalAttackTime!==null){renderFatalAttack();return;}if(deathTime!==null){renderDeath();return;}const enemy=C.ENEMIES[run.stage],last=run.last,isResult=run.phase==='result',p=Math.min(animationTime/(last?A.resultDuration(last):875),1),hit=isResult&&animationTime>=250;ctx.save();
    if(hit&&animationTime<300&&!settings.reduced){const intensity=last.grade==='PERFECT'?4:2;ctx.translate(Math.sin(animationTime*.3)*intensity,Math.cos(animationTime*.17)*intensity);}
    ctx.drawImage(images['bg_'+enemy.region],0,0,512,336);
    const bottomShade=ctx.createLinearGradient(0,200,0,336);bottomShade.addColorStop(0,'transparent');bottomShade.addColorStop(1,'#0b1b2444');ctx.fillStyle=bottomShade;ctx.fillRect(0,200,512,136);
    const sceneTime=blind()&&run.phase==='holding'?holdVisualTime:visualTime;
    let heroX=72,enemyX=316,heroY=107,enemyY=107,heroRow=0,frame=Math.floor(sceneTime/125)%4,enemyScale=enemy.id==='demon_king'?1.3:1;
    if(stageTime<A.duration('run')&&run.phase!=='holding'){const offset=(1-Math.min(1,stageTime/A.duration('run')))**2;heroX-=160*offset;enemyX+=190*offset;heroRow=1;}
    if(run.phase==='holding')heroRow=2;
    if(run.mode==='defense'&&!isResult){enemyX-=8;enemyY-=Math.sin(sceneTime/150)*2;}
    if(isResult){if(last.mode==='attack'){if(animationTime<A.duration('attack')){heroRow=3;frame=Math.min(3,Math.floor(animationTime/125));}heroX+=Math.sin(p*Math.PI)*90;if(hit)enemyX+=Math.sin(p*Math.PI)*18;}else{enemyX-=Math.sin(p*Math.PI)*92;heroRow=hit&&last.damage>0?4:2;frame=Math.min(3,Math.floor(animationTime/140));}}
    const enemyDead=run.enemyHp===0&&hit,alpha=enemyDead?Math.max(0,1-(animationTime-C.SCENE_TIMES.enemyFadeStart)/(C.SCENE_TIMES.enemyFadeEnd-C.SCENE_TIMES.enemyFadeStart)):1;
    for(const [x,y,w,a]of [[heroX+64+(A.shadowX-A.anchorX)*A.renderScale,230,38*A.renderScale,1],[enemyX+64,230,enemyScale*43,alpha]]){ctx.globalAlpha=a;ctx.fillStyle='#06181866';ctx.beginPath();ctx.ellipse(x,y,w,7,0,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;
    let heroAction='idle',heroFrame=A.frame('idle',sceneTime,true);
    if(stageTime<A.duration('run')&&run.phase!=='holding'){heroAction='run';heroFrame=A.frame('run',stageTime);}
    if(run.mode==='defense'){
      heroAction='guard';heroFrame=A.frame('guard',sceneTime-guardVisualStart);
      if(isResult){heroAction=last.grade==='PERFECT'?'perfect':last.grade==='MISS'&&animationTime<A.duration('break')?'break':'damage';const offset=last.grade==='MISS'&&heroAction==='damage'?A.duration('break'):0;heroFrame=A.frame(heroAction,animationTime-offset);}
    }else if(run.phase==='holding'){heroAction='charge';heroFrame=blind()?0:A.frame('charge',performance.now()-holdStart);}
    else if(isResult&&last.mode==='attack'&&animationTime<A.duration('attack')){heroAction='attack';heroFrame=A.frame('attack',animationTime);}
    drawHero(heroAction,heroFrame,heroX,heroY);
    let enemyRow=run.mode==='defense'?1:0,enemyFrame=Math.floor(sceneTime/180)%4;
    if(run.mode==='defense'&&enemy.id!=='slime')enemyFrame=Math.min(3,Math.floor(Math.max(0,sceneTime-guardVisualStart)/180));
    if(isResult){if(last.mode==='defense'){enemyRow=2;enemyFrame=Math.min(3,Math.floor(animationTime/140));}else if(hit&&last.damage>0){enemyRow=enemyDead?4:3;enemyFrame=Math.min(3,Math.floor((animationTime-170)/(enemyDead?280:100)));}}
    drawEnemy(enemy.id,enemyRow,enemyFrame,enemyX,enemyY,alpha);
    if(run.phase==='holding'&&!blind()){const t=Math.min(1.5,(performance.now()-holdStart)/1000);ctx.strokeStyle=run.mode==='defense'?'#87d6f8':'#edca7b';ctx.lineWidth=2;ctx.globalAlpha=.3+t*.3;ctx.beginPath();ctx.ellipse(heroX+65,heroY+76,36+t*4,49,0,Math.PI*.75,Math.PI*2.2);ctx.stroke();ctx.globalAlpha=1;}

    if(hit&&animationTime<470){const a=1-(animationTime-170)/300;ctx.save();ctx.globalAlpha=Math.max(0,a);const sx=last.mode==='attack'?enemyX+45:heroX+113,sy=heroY+65;ctx.strokeStyle=last.mode==='defense'?'#cff6ff':last.grade==='PERFECT'?'#fff1ad':'#f0eaca';ctx.lineWidth=last.grade==='PERFECT'?9:4;if(last.grade!=='MISS'||last.mode==='defense'){ctx.beginPath();ctx.moveTo(sx-40,sy+50);ctx.quadraticCurveTo(sx+75,sy+15,sx+35,sy-48);ctx.stroke();for(let i=0;i<12;i++){const angle=i*Math.PI/6,r=12+(animationTime-170)*.23;ctx.fillStyle=i%2?'#fff9dc':ctx.strokeStyle;ctx.fillRect(sx+Math.cos(angle)*r,sy+Math.sin(angle)*r,3,3);}}ctx.restore();}
    if(enemy.region==='volcano'||enemy.region==='demon_castle'){ctx.fillStyle=enemy.region==='volcano'?'#ffb66188':'#b093e888';for(let i=0;i<12;i++){const x=(i*67+Math.sin(sceneTime/900+i)*10)%512,y=336-((sceneTime/30+i*37)%336);ctx.fillRect(x,y,2,2);}}
    if(isResult&&last.mode==='attack'&&last.grade==='PERFECT'&&animationTime<170){ctx.save();ctx.globalAlpha=animationTime<90?1:Math.max(0,(170-animationTime)/80);ctx.drawImage(images.attack_perfect,0,24,512,288);ctx.restore();}
    ctx.restore();
  }
  function frame(now){if(screen==='title'){const elapsed=Math.max(0,now-titleClockStart);$('title-seconds').textContent=String(Math.floor(elapsed/1000)%60).padStart(2,'0');$('title-second-progress').style.transform=`scaleX(${(elapsed%1000)/1000})`;}const dt=Math.min(100,Math.max(0,now-previous));previous=now;audio.tick(dt);if(!paused){visualTime+=dt;if(revealTime!==null){revealTime+=dt;fadeScene(Math.max(0,1-revealTime/C.SCENE_TIMES.reveal));if(revealTime>=C.SCENE_TIMES.reveal)revealTime=null;}if(screen==='play'&&run){stageTime+=dt;
      if(warningTime>0)warningTime=Math.max(0,warningTime-dt);
      if(run.phase==='holding'){const elapsed=(now-holdStart)/1000;if(!blind())$('dial-progress').style.strokeDashoffset=String(647.168*(1-Math.min(1,elapsed/1.5)));if(elapsed>=C.CONFIG.maxHold)releaseHold(true);}
      if(fatalAttackTime!==null)advanceFatalAttack(dt);
      else if(deathTime!==null)advanceDeath(dt);
      else if(run.phase==='result'){animationTime+=dt;if(!impactShown&&animationTime>=250){impactShown=true;hud();const r=run.last;$('hit-label').textContent=r.mode==='defense'?(r.damage===0?'JUST GUARD':'−'+r.damage):r.damage===0?'MISS':r.damage;$('hit-label').style.color=r.mode==='defense'?(r.damage===0?'#b9f4ff':'#ffa8a0'):'#fff0ad';if(r.mode==='defense'&&r.damage>0)audio.playSE('hero_damage');}
        const duration=run.enemyHp===0?C.SCENE_TIMES.enemyDefeat:A.resultDuration(run.last);
        if(animationTime>=duration){const result=C.finish(run);if(result==='shop'||result==='clear'){if(result==='shop')shop();else end(true);}else if(result==='over')end(false);else{warningTime=result==='defense'?600:0;if(result==='defense')guardVisualStart=visualTime;readyUI();if(result==='defense')audio.playSE('guard_warning');}}
      }
      render();
    }}requestAnimationFrame(frame);}
  async function load(){const paths={attack_perfect:'./assets/backgrounds/attack_perfect512.png',allclear:'./assets/backgrounds/allclear512.png',gameover:'./assets/backgrounds/gameover512.png',itemshop:'./assets/backgrounds/itemshop512.png',attack_button:'./assets/ui/Attack_button.png',shield_button:'./assets/ui/Shield_button.png'};for(const name of ['idle','run','charge','attack','damage','down','guard','perfect','break'])paths['hero_'+name]=`./assets/hero/${name}.png`;for(const e of C.ENEMIES)paths[e.id]=E.specs[e.id].path;for(const region of ['plains','desert','volcano','demon_castle'])paths['bg_'+region]=`./assets/backgrounds/bg_${region}512.png`;
    try{await Promise.all(Object.entries(paths).map(([key,path])=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{images[key]=img;resolve();};img.onerror=()=>reject(new Error(path));img.src=path;})));loaded=true;$('start-button').disabled=false;$('start-button').textContent='冒険をはじめる →';$('footer-status').textContent='準備完了 · 強化を重ねて、魔王城へ';}catch(error){$('start-button').textContent='素材を読み込めませんでした';$('load-note').textContent='assetsフォルダをindex.htmlと同じ場所に置いてください。 '+error.message;}}
  load();requestAnimationFrame(frame);
})();
